apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: bhoopeshsharma/k8s_python_demo_code:latest
  imagePullSecrets:
  - name: regcred

