apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80

    # Liveness Probe (checks every 10s, starts after 5s)
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10

    # Readiness Probe (checks every 5s, starts after 5s)
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
