apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: /data/config
  storageClassName: "shared"
